spring:
  application:
    name: Loveable-clone
    description: This is Loveable clone project
  datasource:
    url: "jdbc:mysql://localhost:32772/testDB?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: Nidhi2004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true







